### ISSUE TITLE
please provide build instructions

### ISSUE THREAD

**Issue by manuongithub** [Kademi/keditor#179]
Hi,

I'm getting syntaxerrors when I try to build using npm run build

Can you please help as I'm not able to figure out the issue from the output.

The logs are attached under:
```
ERROR in ./src/keditor/sidebar/showSettingForm.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/manu.mehrotra/Downloads/keditor-master 2/src/keditor/sidebar/showSettingForm.js: Unexpected token (4:1)

  2 | import SETTING_CATEGORY from '../constants/settingCategory';
  3 | import closeSidebar from './closeSidebar';export default function (target, settingType, settingCategory, settingTitle, initFunction, showFunction, functionContext) {let self = this;let sidebar = self.sidebar;let sidebarTitle = self.sidebarTitle;let sidebarBody = self.sidebarBody;let settingForm = sidebarBody.children(`.${CSS_CLASS.SETTING_FORM}[data-setting-type="${settingType}"][data-setting-category="${settingCategory}"]`);if (settingForm.length === 0) {if (typeof initFunction === 'function') {settingForm = $(`<divdata-setting-type="${settingType}"data-setting-category="${settingCategory}"class="${CSS_CLASS.UI} ${CSS_CLASS.SETTING_FORM}"></div>`);let loadingText = $(`<span class="${CSS_CLASS.SETTING_FORM_LOADING}" />`).html('Loading...');sidebarBody.append(settingForm);settingForm.append(loadingText);$.when(initFunction.call(functionContext, settingForm, self)).done(function () {setTimeout(function () {loadingText.remove();if (typeof showFunction === 'function') {showFunction.call(functionContext, settingForm, target, self);}}, 100);});}} else {if (settingForm.hasClass(CSS_CLASS.STATE_ACTIVE) && (target.is(self.settingContainer) || target.is(self.settingComponent))) {closeSidebar.call(self);return;} else {if (typeof showFunction === 'function') {showFunction.call(functionContext, settingForm, target, self);}}}self.settingComponent = null;self.settingContainer = null;switch (settingCategory) {case SETTING_CATEGORY.COMPONENT:self.settingComponent = target;break;case SETTING_CATEGORY.CONTAINER:self.settingContainer = target;break;default:// Do nothing}sidebarBody.children(`.${CSS_CLASS.STATE_ACTIVE}`).removeClass(CSS_CLASS.STATE_ACTIVE);sidebarTitle.html(settingTitle);settingForm.addClass(CSS_CLASS.STATE_ACTIVE);sidebar.addClass(CSS_CLASS.STATE_OPENED);
> 4 | }
    |  ^
    at Parser.raise (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:6344:17)
    at Parser.unexpected (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:7659:16)
    at Parser.parseExprAtom (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:8828:20)
    at Parser.parseExprSubscripts (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:8413:23)
    at Parser.parseMaybeUnary (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:8393:21)
    at Parser.parseExprOps (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:8280:23)
    at Parser.parseMaybeConditional (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:8253:23)
    at Parser.parseMaybeAssign (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:8200:21)
    at Parser.parseExpression (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:8148:23)
    at Parser.parseStatementContent (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9917:23)
    at Parser.parseStatement (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9788:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10364:25)
    at Parser.parseBlockBody (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10351:10)
    at Parser.parseBlock (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10335:10)
    at Parser.parseFunctionBody (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9408:24)
    at Parser.parseFunctionBodyAndFinish (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9378:10)
    at /Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10498:12
    at Parser.withTopicForbiddingContext (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9683:14)
    at Parser.parseFunction (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10497:10)
    at Parser.parseExportDefaultExpression (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10960:19)
    at Parser.parseExport (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10868:31)
    at Parser.parseStatementContent (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9892:27)
    at Parser.parseStatement (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9788:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10364:25)
    at Parser.parseBlockBody (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:10351:10)
    at Parser.parseTopLevel (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:9717:10)
    at Parser.parse (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:11233:17)
    at parse (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/parser/lib/index.js:11269:38)
    at parser (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /Users/manu.mehrotra/Downloads/keditor-master 2/node_modules/@babel/core/lib/transform.js:34:34
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
 @ ./src/keditor/sidebar/openSidebar.js 4:0-48 14:11-26 14:38-53
 @ ./src/keditor/index.js
```

**Comment by manuongithub** [comment]
this piece in webpack.config.js is causing build issues as it comments out whole files which have even one line of comment in them:

{
                        loader: 'string-replace-loader',
                        options: {
                            multiple: [
                                {
                                    search: '@{version}',
                                    replace: packageJson.version
                                },
                                {
                                    search: '\\n\\s+',
                                    replace: '',
                                    flags: 'g'
                                }
                            ]
                        }
                    }

so I had to remove these to fix the build for me

**Comment by ducdhm** [comment]
@manuongithub Which version of npm are you using? I am still running `npm run build` normally.

**Comment by ducdhm** [comment]
@manuongithub 
JFYI: 
 * `npm run build` for production mode
 * `npm rundev` for dev mode include watching and build

**Comment by ducdhm** [comment]
Duplicated with https://github.com/Kademi/keditor/issues/178

**Comment by manuongithub** [comment]
npm version - 6.10.0
